#ifndef ENTRYPOINTVOID
#define ENTRYPOINTVOID(name,params,args) ENTRYPOINT(void,name,params,args)
#endif
#ifndef ENTRYPOINT_EXTENSIONS_BEGIN
#define ENTRYPOINT_EXTENSIONS_BEGIN()
#endif

ENTRYPOINT(ALCcontext *,alcGetCurrentContext,(void),())
ENTRYPOINT(ALCdevice *,alcGetContextsDevice,(ALCcontext *context),(context))
ENTRYPOINT(ALCboolean,alcIsExtensionPresent,(ALCdevice *device, const ALCchar *extname),(device,extname))
ENTRYPOINT(void *,alcGetProcAddress,(ALCdevice *device, const ALCchar *funcname),(device,funcname))
ENTRYPOINT(ALCenum,alcGetEnumValue,(ALCdevice *device, const ALCchar *enumname),(device,enumname))
ENTRYPOINT(const ALCchar *,alcGetString,(ALCdevice *device, ALCenum param),(device,param))
ENTRYPOINT(ALCdevice *,alcCaptureOpenDevice,(const ALCchar *devicename, ALCuint frequency, ALCenum format, ALCsizei buffersize),(devicename,frequency,format,buffersize))
ENTRYPOINT(ALCboolean,alcCaptureCloseDevice,(ALCdevice *device),(device))
ENTRYPOINT(ALCdevice *,alcOpenDevice,(const ALCchar *devicename),(devicename))
ENTRYPOINT(ALCboolean,alcCloseDevice,(ALCdevice *device),(device))
ENTRYPOINT(ALCcontext *,alcCreateContext,(ALCdevice *device, const ALCint* attrlist),(device,attrlist))
ENTRYPOINT(ALCboolean,alcMakeContextCurrent,(ALCcontext *ctx),(ctx))
ENTRYPOINTVOID(alcProcessContext,(ALCcontext *ctx),(ctx))
ENTRYPOINTVOID(alcSuspendContext,(ALCcontext *ctx),(ctx))
ENTRYPOINTVOID(alcDestroyContext,(ALCcontext *ctx),(ctx))
ENTRYPOINT(ALCenum,alcGetError,(ALCdevice *device),(device))
ENTRYPOINTVOID(alcGetIntegerv,(ALCdevice *device, ALCenum param, ALCsizei size, ALCint *values),(device,param,size,values))
ENTRYPOINTVOID(alcCaptureStart,(ALCdevice *device),(device))
ENTRYPOINTVOID(alcCaptureStop,(ALCdevice *device),(device))
ENTRYPOINTVOID(alcCaptureSamples,(ALCdevice *device, ALCvoid *buffer, ALCsizei samples),(device,buffer,samples))
ENTRYPOINTVOID(alDopplerFactor,(ALfloat value),(value))
ENTRYPOINTVOID(alDopplerVelocity,(ALfloat value),(value))
ENTRYPOINTVOID(alSpeedOfSound,(ALfloat value),(value))
ENTRYPOINTVOID(alDistanceModel,(ALenum model),(model))
ENTRYPOINTVOID(alEnable,(ALenum capability),(capability))
ENTRYPOINTVOID(alDisable,(ALenum capability),(capability))
ENTRYPOINT(ALboolean,alIsEnabled,(ALenum capability),(capability))
ENTRYPOINT(const ALchar *,alGetString,(const ALenum param),(param))
ENTRYPOINTVOID(alGetBooleanv,(ALenum param, ALboolean *values),(param,values))
ENTRYPOINTVOID(alGetIntegerv,(ALenum param, ALint *values),(param,values))
ENTRYPOINTVOID(alGetFloatv,(ALenum param, ALfloat *values),(param,values))
ENTRYPOINTVOID(alGetDoublev,(ALenum param, ALdouble *values),(param,values))
ENTRYPOINT(ALboolean,alGetBoolean,(ALenum param),(param))
ENTRYPOINT(ALint,alGetInteger,(ALenum param),(param))
ENTRYPOINT(ALfloat,alGetFloat,(ALenum param),(param))
ENTRYPOINT(ALdouble,alGetDouble,(ALenum param),(param))
ENTRYPOINT(ALboolean,alIsExtensionPresent,(const ALchar *extname),(extname))
ENTRYPOINT(ALenum,alGetError,(void),())
ENTRYPOINT(void *,alGetProcAddress,(const ALchar *funcname),(funcname))
ENTRYPOINT(ALenum,alGetEnumValue,(const ALchar *enumname),(enumname))
ENTRYPOINTVOID(alListenerfv,(ALenum param, const ALfloat *values),(param,values))
ENTRYPOINTVOID(alListenerf,(ALenum param, ALfloat value),(param,value))
ENTRYPOINTVOID(alListener3f,(ALenum param, ALfloat value1, ALfloat value2, ALfloat value3),(param,value1,value2,value3))
ENTRYPOINTVOID(alListeneriv,(ALenum param, const ALint *values),(param,values))
ENTRYPOINTVOID(alListeneri,(ALenum param, ALint value),(param,value))
ENTRYPOINTVOID(alListener3i,(ALenum param, ALint value1, ALint value2, ALint value3),(param,value1,value2,value3))
ENTRYPOINTVOID(alGetListenerfv,(ALenum param, ALfloat *values),(param,values))
ENTRYPOINTVOID(alGetListenerf,(ALenum param, ALfloat *value),(param,value))
ENTRYPOINTVOID(alGetListener3f,(ALenum param, ALfloat *value1, ALfloat *value2, ALfloat *value3),(param,value1,value2,value3))
ENTRYPOINTVOID(alGetListeneri,(ALenum param, ALint *value),(param,value))
ENTRYPOINTVOID(alGetListeneriv,(ALenum param, ALint *values),(param,values))
ENTRYPOINTVOID(alGetListener3i,(ALenum param, ALint *value1, ALint *value2, ALint *value3),(param,value1,value2,value3))
ENTRYPOINTVOID(alGenSources,(ALsizei n, ALuint *names),(n,names))
ENTRYPOINTVOID(alDeleteSources,(ALsizei n, const ALuint *names),(n,names))
ENTRYPOINT(ALboolean,alIsSource,(ALuint name),(name))
ENTRYPOINTVOID(alSourcefv,(ALuint name, ALenum param, const ALfloat *values),(name,param,values))
ENTRYPOINTVOID(alSourcef,(ALuint name, ALenum param, ALfloat value),(name,param,value))
ENTRYPOINTVOID(alSource3f,(ALuint name, ALenum param, ALfloat value1, ALfloat value2, ALfloat value3),(name,param,value1,value2,value3))
ENTRYPOINTVOID(alSourceiv,(ALuint name, ALenum param, const ALint *values),(name,param,values))
ENTRYPOINTVOID(alSourcei,(ALuint name, ALenum param, ALint value),(name,param,value))
ENTRYPOINTVOID(alSource3i,(ALuint name, ALenum param, ALint value1, ALint value2, ALint value3),(name,param,value1,value2,value3))
ENTRYPOINTVOID(alGetSourcefv,(ALuint name, ALenum param, ALfloat *values),(name,param,values))
ENTRYPOINTVOID(alGetSourcef,(ALuint name, ALenum param, ALfloat *value),(name,param,value))
ENTRYPOINTVOID(alGetSource3f,(ALuint name, ALenum param, ALfloat *value1, ALfloat *value2, ALfloat *value3),(name,param,value1,value2,value3))
ENTRYPOINTVOID(alGetSourceiv,(ALuint name, ALenum param, ALint *values),(name,param,values))
ENTRYPOINTVOID(alGetSourcei,(ALuint name, ALenum param, ALint *value),(name,param,value))
ENTRYPOINTVOID(alGetSource3i,(ALuint name, ALenum param, ALint *value1, ALint *value2, ALint *value3),(name,param,value1,value2,value3))
ENTRYPOINTVOID(alSourcePlay,(ALuint name),(name))
ENTRYPOINTVOID(alSourcePlayv,(ALsizei n, const ALuint *names),(n, names))
ENTRYPOINTVOID(alSourcePause,(ALuint name),(name))
ENTRYPOINTVOID(alSourcePausev,(ALsizei n, const ALuint *names),(n, names))
ENTRYPOINTVOID(alSourceRewind,(ALuint name),(name))
ENTRYPOINTVOID(alSourceRewindv,(ALsizei n, const ALuint *names),(n, names))
ENTRYPOINTVOID(alSourceStop,(ALuint name),(name))
ENTRYPOINTVOID(alSourceStopv,(ALsizei n, const ALuint *names),(n, names))
ENTRYPOINTVOID(alSourceQueueBuffers,(ALuint name, ALsizei nb, const ALuint *bufnames),(name,nb,bufnames))
ENTRYPOINTVOID(alSourceUnqueueBuffers,(ALuint name, ALsizei nb, ALuint *bufnames),(name,nb,bufnames))
ENTRYPOINTVOID(alGenBuffers,(ALsizei n, ALuint *names),(n,names))
ENTRYPOINTVOID(alDeleteBuffers,(ALsizei n, const ALuint *names),(n,names))
ENTRYPOINT(ALboolean,alIsBuffer,(ALuint name),(name))
ENTRYPOINTVOID(alBufferData,(ALuint name, ALenum alfmt, const ALvoid *data, ALsizei size, ALsizei freq),(name,alfmt,data,size,freq))
ENTRYPOINTVOID(alBufferfv,(ALuint name, ALenum param, const ALfloat *values),(name,param,values))
ENTRYPOINTVOID(alBufferf,(ALuint name, ALenum param, ALfloat value),(name,param,value))
ENTRYPOINTVOID(alBuffer3f,(ALuint name, ALenum param, ALfloat value1, ALfloat value2, ALfloat value3),(name,param,value1,value2,value3))
ENTRYPOINTVOID(alBufferiv,(ALuint name, ALenum param, const ALint *values),(name,param,values))
ENTRYPOINTVOID(alBufferi,(ALuint name, ALenum param, ALint value),(name,param,value))
ENTRYPOINTVOID(alBuffer3i,(ALuint name, ALenum param, ALint value1, ALint value2, ALint value3),(name,param,value1,value2,value3))
ENTRYPOINTVOID(alGetBufferfv,(ALuint name, ALenum param, ALfloat *values),(name,param,values))
ENTRYPOINTVOID(alGetBufferf,(ALuint name, ALenum param, ALfloat *value),(name,param,value))
ENTRYPOINTVOID(alGetBuffer3f,(ALuint name, ALenum param, ALfloat *value1, ALfloat *value2, ALfloat *value3),(name,param,value1,value2,value3))
ENTRYPOINTVOID(alGetBufferi,(ALuint name, ALenum param, ALint *value),(name,param,value))
ENTRYPOINTVOID(alGetBuffer3i,(ALuint name, ALenum param, ALint *value1, ALint *value2, ALint *value3),(name,param,value1,value2,value3))
ENTRYPOINTVOID(alGetBufferiv,(ALuint name, ALenum param, ALint *values),(name,param,values))

ENTRYPOINT_EXTENSIONS_BEGIN()
ENTRYPOINTVOID(alTracePushScope,(const ALchar *str),(str))
ENTRYPOINTVOID(alTracePopScope,(void),())
ENTRYPOINTVOID(alTraceMessage,(const ALchar *str),(str))
ENTRYPOINTVOID(alTraceBufferLabel,(ALuint name, const ALchar *str),(name,str))
ENTRYPOINTVOID(alTraceSourceLabel,(ALuint name, const ALchar *str),(name,str))
ENTRYPOINTVOID(alcTraceDeviceLabel,(ALCdevice *device, const ALchar *str),(device,str))
ENTRYPOINTVOID(alcTraceContextLabel,(ALCcontext *ctx, const ALchar *str),(ctx,str))

#undef ENTRYPOINT
#undef ENTRYPOINTVOID
#undef ENTRYPOINT_EXTENSIONS_BEGIN

